### ISSUE TITLE
suchtube --help giving Unexpected token error in node version 6.11.4

### ISSUE THREAD

**Issue by rjoydip-zz** [markets/suchtube#9]
exports.start = async () => {
                      ^
SyntaxError: Unexpected token (

**Comment by markets** [comment]
Hi @Rjoydip thanks for your report! 

Actually this package is tested against Node v7+ (7, 8, 9), as you can see here https://github.com/markets/suchtube/blob/master/.travis.yml#L6.

I'm not sure if there is an easy way to support v6 (I'm new to Node module development), since I use a async/await, which was introduced on v7 if I'm not wrong. I don't want to introduce babel and webpack to the build process. So, I'm going to improve docs to reflect current supported versions. You can easily manage different Node versions with a version manager like: creationix/nvm or tj/n.

**Comment by rjoydip-zz** [comment]
Yes it will be good to mention over docs also you can keep a check and rather throwing an error directly you can echo a message .You can check this https://github.com/tc39/ecmascript-asyncawait/issues/78. I hope this will help you. 👍

**Comment by markets** [comment]
Hi @Rjoydip I just pushed https://github.com/markets/suchtube/commit/3e38930e206fa2276c4e91fa2b523ab45bbda4f3. Thanks!

**Comment by rjoydip-zz** [comment]
👍
